"""add_config_name_to_llm_configs

Revision ID: 1822712c5e11
Revises: 378b065197a3
Create Date: 2026-01-06 22:31:34.848807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1822712c5e11'
down_revision: Union[str, None] = '378b065197a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('config_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configs', 'config_name')
    # ### end Alembic commands ###
