"""Add oauth_credentials table for drive connections

Revision ID: bfc70a27b953
Revises: 43c3d5f14a36
Create Date: 2026-01-06 16:45:03.986395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfc70a27b953'
down_revision: Union[str, None] = '43c3d5f14a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create oauth_credentials table
    op.create_table('oauth_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('credentials_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_credentials_user_id'), 'oauth_credentials', ['user_id'], unique=False)
    
    # Note: langchain_pg_collection and langchain_pg_embedding are managed by LangChain/PGVector
    # and should not be dropped by Alembic migrations. They are created/dropped by the application.
    # Note: kyt_preview_2024 appears to be a test/legacy table - keeping it for now.
    
    # Drop unique constraint on user_settings if it exists (replaced by unique index)
    # Use try/except to handle case where constraint doesn't exist
    try:
        op.drop_constraint('user_settings_user_id_key', 'user_settings', type_='unique')
    except Exception:
        # Constraint doesn't exist or already dropped, which is fine
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop oauth_credentials table
    op.drop_index(op.f('ix_oauth_credentials_user_id'), table_name='oauth_credentials')
    op.drop_table('oauth_credentials')
    
    # Note: langchain_pg_collection and langchain_pg_embedding are managed by LangChain/PGVector
    # and should not be recreated by Alembic migrations.
    # Note: kyt_preview_2024 is a legacy table - not recreating it.
    
    # Recreate unique constraint on user_settings if needed
    # This is optional - the unique index should be sufficient
    # op.create_unique_constraint('user_settings_user_id_key', 'user_settings', ['user_id'])
    # ### end Alembic commands ###
